- name: Update system and required packages
  become: true
  block:
    - apt: 
        update_cache: yes

    - name: Install Packages for DS
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - golang 
        - golang-doc
        - python3 
        - python3-doc 
        - python3-dev
        - build-essential
