---
- hosts: Computer-Networks
  become: yes
  tasks:
    - name: Install Software for Computer Networks Lab
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - scapy
        - iptables
        - wireshark
        - ebtables
        - ufw
        - nmap
        - quagga
        - ftp
        - isc-dhcp-server
        - ntp
        - iperf
        - iperf3
        - echoping
        - tftp
        - telnet
        - mate-desktop-environment-extras
        - mate-themes
        - lightdm
        - lightdm-gtk-greeter
        - ubuntu-artwork
        - update-manager
        - traceroute
        - tree
        - snmp
        - psad
        - quagga-doc


    - name: Copy Configuration files
      copy:
        src: ~/ansible/ComputerNetworks/CN_R3/configuration-files/
        dest: /etc/

    - name: Copy installation script
      copy:
        src: ~/ansible/ComputerNetworks/CN_R3/installation.sh
        dest: /tmp/

    - name: Run the script
      shell: sh /tmp/installation.sh

    - name: Copy Lightdm Configuration files
      copy:
        src: ~/ansible/ComputerNetworks/CN_R1/lightdm/
        dest: /etc/lightdm/

    - name: Enable lightdm
      shell: "{{ item }}"
      with_items:
        - ln -s /lib/systemd/system/lightdm.service /etc/systemd/systemd/display-manager.service
        - systemctl disable lightdm.service

    - name: Disable dhcpd
      shell: systemctl disable isc-dhcp-server
