---
- name: Start Services
  block:
    - name: Enable lightdm
      service:
        name: lightdm.service
        enabled: yes
        state: started

    - name: frr
      service:
        name: frr
        enabled: yes
        state: started
  become: true


