---
- hosts: Network-Security
  become: true
  tasks:
    - name: Update the system
      apt:
        update_cache: yes
    - name: Install Packages
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - wireshark
        - scapy
        - iptables
        - ebtables
        - ufw
        - nmap
        - quagga
        - isc-dhcp-server
        - snmp
        - mysql-server
        - mysql-client
        - ntp
        - psad
        - bind9
        - bind9utils
        - bind9-doc
        - mate-desktop-environment-extras
        - mate-themes
        - lightdm
        - lightdm-gtk-greeter
        - ubuntu-artwork
        - update-manager
        - traceroute
        - tree


    - name: Copy Configuration files
      copy:
        src: ~/ansible/NetSec/Ext-router/configuration-files/
        dest: /etc/

    - name: Copy Lightdm Configuration files
      copy:
        src: ~/ansible/NetSec/Ext-router/lightdm/
        dest: /etc/lightdm/

    - name: Enable lightdm
      shell: "{{ item }}"
      with_item:
        - ln -s /lib/systemd/system/lightdm.service /etc/systemd/systemd/display-manager.service
        - systemctl enable lightdm.service

    - name: Enable dhcpd
      shell: systemctl enable isc-dhcp-server
