---
 - name: Install Software for Computer Networks Lab
   apt:
     pkg: "{{ item }}"
     state: present
   with_items:
     - scapy
     - iptables
     - wireshark
     - ebtables
     - ufw
     - nmap
     - quagga
     - ftp
     - isc-dhcp-server
     - ntp
     - iperf
     - iperf3
     - echoping
     - tftp
     - telnet
     - mate-desktop-environment-extras 
     - mate-themes
     - lightdm 
     - lightdm-gtk-greeter 
     - ubuntu-artwork 
     - update-manager

   notify: Disable lightdm
   become: true  
