---
- name: download source of frr
  git:
    repo: "https://github.com/FRRouting/frr.git"
    dest: "{{ frr.location }}"
    version: stable/5.0
  
- name: configure frr
  become_user: "{{ frr.user }}"
  become: true        
  become_method: sudo
  block:
    - name: Run bootstrap.sh
      shell: ./bootstrap.sh
      args:
        chdir: "{{ frr.location }}" 

    - name: Run configure file
      shell: ./configure --prefix=/usr/local --enable-exampledir=/usr/share/doc/frr/examples/  --localstatedir=/var/run/frr --sbindir=/usr/lib/frr  --sysconfdir=/etc/frr  --enable-isis-topology --enable-isis-te 
      args:
        chdir: "{{ frr.location }}" 

    - name: make
      make:
        chdir: "{{ frr.location }}" 
        
    - name: make install
      make:
        chdir: "{{ frr.location }}" 
        target: install

    - shell: export PATH=/usr/lib/frr     
