- name: Update system and required packages
  become: true
  block:
    - apt: 
        update_cache: yes

    - name: Install Packages for PL
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - lxde
        - lxde-common
        - lxsession-logout
        - ocaml-nox
        - ocaml
        - clisp 
        - cl-closer-mop 
        - cl-launch
        - clisp-doc 
        - clisp-dev
        - php 
        - php-doc 
        - php-dev
        - ruby
        - ruby-dev
        - julia 
        - julia-doc 
        - julia-common 
        - flex 
        - flex-doc 
        - libelf-dev
        - bison 
        - bison-doc 
        - libbison-dev
        - golang 
        - golang-doc
        - gfortran 
        - gfortran-doc 
        - gfortran-multilib
        - python3 
        - python3-doc 
        - python3-dev 
        - idle3 
        - libpython3-stdlib
        - swi-prolog 
        - swi-prolog-doc
        - mit-scheme 
        - mit-scheme-doc 
        - mit-scheme-dbg
        - ghc 
        - ghc-doc 
        - ghc-prof 
        - ghc-mod-el 
        - haskell-doc 
        - haskell98-report 
        - haskell98-tutorial
        - clojure1.6
        - smlnj 
        - smlnj-doc 
        - smlnj-runtime
        - aspectj 
        - aspectj-doc 
        - aspectc++

    - name: Install Rust
      shell: curl -sf -L -y https://static.rust-lang.org/rustup.sh | sh

    - name: Install Pharo
      shell: curl -L https://get.pharo.org/64/ | bash

    - name: Purge Openbox
      apt:
        pkg: openbox
        state: absent
        purge: yes

    - name: Remove openbox.desktop file
      file:
         state: absent
         path: /usr/share/xsessions/openbox.desktop    
