---
- name: add ip masquerade rules
  become: true
  shell: /
    iptables -t nat -A POSTROUTING -o eth0 -d 128.238.77.36 -j MASQUERADE
    iptables-save| tee /etc/iptables.conf

- name: Create rc0.local persistent
  become: true
  shell: /
    sudo touch /etc/rc.local
    sudo echo "" > /etc/rc.local
    sudo echo "#!/bin/sh -e" >> /etc/rc.local
    sudo echo "iptables-restore < /etc/iptables.conf" >> /etc/rc.local
    sudo echo "exit 0" >> /etc/rc.local
    chmod +x /etc/rc.local