---
- name: Update system and required packages
  block:
    - apt: 
        update_cache: yes

    - name: Install Software for Computer Networks Lab
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
         - autoconf
         - automake
         - autotools-dev
         - bind9
         - bison
         - build-essential
         - cmake
         - debhelper
         - dejagnu
         - ebtables
         - echoping
         - flex
         - ftp
         - gawk
         - git
         - install-info
         - iperf
         - iperf3
         - iptables
         - iptables-persistent
         - isc-dhcp-server
         - libc-ares-dev
         - libjson-c-dev
         - libpam0g-dev
         - libpcre3-dev
         - libprotobuf-c-dev
         - libpython-dev
         - libreadline-dev
         - libsnmp-dev
         - libsystemd-dev
         - libtool
         - libzmq3-dev
         - libzmq5
         - lightdm
         - lightdm-gtk-greeter
         - make
         - mate-desktop-environment-extras
         - mate-themes
         - net-tools
         - nmap
         - ntp
         - perl
         - pkg-config
         - protobuf-c-compiler
         - python3-dev
         - python3-pytest
         - python3-sphinx
         - python-ipaddr
         - python-ipaddress
         - python-pytest
         - python-sphinx
         - scapy
         - swig
         - telnet
         - texinfo
         - tftp
         - traceroute
         - tree
         - ufw
         - update-manager
         - vim
         - wireshark
      notify: Enable lightdm
  become: true        
